#!/bin/bash
set -e

AIRSS_URL='http://bit.ly/2KtvEWU'

curl -L -o AIRSS.tgz $AIRSS_URL
tar zxf AIRSS.tgz
rm AIRSS.tgz

mv airss-* airss
cd airss
export FC=gfortran
make all
make install

# Copy the executable to the folder
mkdir -p ~/.local/bin
cp bin/* ~/.local/bin/

# Make a symbolic link to AIRSS's examples
ln -s ~/airss/examples ~/examples

# Append welcome message to bashrc

cat >> $HOME/.bashrc << EOM
# Let the user start in the examples folder
cd examples
# Print AIRSS banner
head -n 10 $HOME/airss/README
echo ""

# Print a list of examples
echo -e "List of AIRSS examples that can be run now:\n"
head -n 14 $HOME/examples/README
echo -e 'See README file at this directoy for a full list of examples\n'
echo -e 'To read the overall README, use `less ~/airss/README`\n'
echo -e 'To get started, please read about the first example with `less 1.1/README`\n'
echo -e 'Hint: Click the Jupyter Logo at the top left to browse the files\n'
EOM
