#!/bin/bash
set -e

# Replace with the currect user id
sed -i -e "s|WORKSPACE_ID|/user/${JUPYTERHUB_USER}/lab|g" $HOME/.jupyterlab-workspace.json

# Import the workspace into JupyterLab
jupyter lab workspaces import $HOME/.jupyterlab-workspace.json \
  --NotebookApp.base_url=user/${JUPYTERHUB_USER}

exec "$@"